"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Put = exports.Post = exports.Get = exports.Delete = exports.Controller = void 0;
var controller_1 = require("./controller");
Object.defineProperty(exports, "Controller", { enumerable: true, get: function () { return controller_1.Controller; } });
var delete_1 = require("./delete");
Object.defineProperty(exports, "Delete", { enumerable: true, get: function () { return delete_1.Delete; } });
var get_1 = require("./get");
Object.defineProperty(exports, "Get", { enumerable: true, get: function () { return get_1.Get; } });
var post_1 = require("./post");
Object.defineProperty(exports, "Post", { enumerable: true, get: function () { return post_1.Post; } });
var put_1 = require("./put");
Object.defineProperty(exports, "Put", { enumerable: true, get: function () { return put_1.Put; } });
